<?php

namespace Modules\Register\Database\Seeders;

use Illuminate\Database\Seeder;
use Modules\Register\Entities\Country;

class CountryTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Country::insert([
            ['fips_code' => '00', 'iso_code' => '00', 'full_name' => 'World'],
            ['fips_code' => 'AA', 'iso_code' => 'AW', 'full_name' => 'Aruba'],
            ['fips_code' => 'AC', 'iso_code' => 'AG', 'full_name' => 'Antigua and Barbuda'],
            ['fips_code' => 'AE', 'iso_code' => 'AE', 'full_name' => 'United Arab Emirates'],
            ['fips_code' => 'AF', 'iso_code' => 'AF', 'full_name' => 'Afghanistan'],
            ['fips_code' => 'AG', 'iso_code' => 'DZ', 'full_name' => 'Algeria'],
            ['fips_code' => 'AJ', 'iso_code' => 'AZ', 'full_name' => 'Azerbaijan'],
            ['fips_code' => 'AL', 'iso_code' => 'AL', 'full_name' => 'Albania'],
            ['fips_code' => 'AM', 'iso_code' => 'AM', 'full_name' => 'Armenia'],
            ['fips_code' => 'AN', 'iso_code' => 'AD', 'full_name' => 'Andorra'],
            ['fips_code' => 'AO', 'iso_code' => 'AO', 'full_name' => 'Angola'],
            ['fips_code' => 'AQ', 'iso_code' => 'AS', 'full_name' => 'American Samoa'],
            ['fips_code' => 'AR', 'iso_code' => 'AR', 'full_name' => 'Argentina'],
            ['fips_code' => 'AS', 'iso_code' => 'AU', 'full_name' => 'Australia'],
            ['fips_code' => 'AT', 'iso_code' => 'A1', 'full_name' => 'Ashmore and Cartier Islands'], #unofficialISO
            ['fips_code' => 'AU', 'iso_code' => 'AT', 'full_name' => 'Austria'],
            ['fips_code' => 'AV', 'iso_code' => 'AI', 'full_name' => 'Anguilla'],
            ['fips_code' => '--', 'iso_code' => 'AX', 'full_name' => 'Aland Islands'],
            ['fips_code' => 'AY', 'iso_code' => 'AQ', 'full_name' => 'Antarctica'],
            ['fips_code' => 'BA', 'iso_code' => 'BH', 'full_name' => 'Bahrain'],
            ['fips_code' => 'BB', 'iso_code' => 'BB', 'full_name' => 'Barbados'],
            ['fips_code' => 'BC', 'iso_code' => 'BW', 'full_name' => 'Botswana'],
            ['fips_code' => 'BD', 'iso_code' => 'BM', 'full_name' => 'Bermuda'],
            ['fips_code' => 'BE', 'iso_code' => 'BE', 'full_name' => 'Belgium'],
            ['fips_code' => 'BF', 'iso_code' => 'BS', 'full_name' => 'Bahamas, The'],
            ['fips_code' => 'BG', 'iso_code' => 'BD', 'full_name' => 'Bangladesh'],
            ['fips_code' => 'BH', 'iso_code' => 'BZ', 'full_name' => 'Belize'],
            ['fips_code' => 'BK', 'iso_code' => 'BA', 'full_name' => 'Bosnia and Herzegovina'],
            ['fips_code' => 'BL', 'iso_code' => 'BO', 'full_name' => 'Bolivia (Plurinational State of)'],
            ['fips_code' => 'TB', 'iso_code' => 'BL', 'full_name' => 'Saint Barthelemy'],
            ['fips_code' => 'BM', 'iso_code' => 'MM', 'full_name' => 'Myanmar'],
            ['fips_code' => 'BN', 'iso_code' => 'BJ', 'full_name' => 'Benin'],
            ['fips_code' => 'BO', 'iso_code' => 'BY', 'full_name' => 'Belarus'],
            ['fips_code' => 'BP', 'iso_code' => 'SB', 'full_name' => 'Solomon Islands'],
            ['fips_code' => 'BQ', 'iso_code' => 'A2', 'full_name' => 'Navassa Island'], #unofficialISO
            ['fips_code' => 'BR', 'iso_code' => 'BR', 'full_name' => 'Brazil'],
            ['fips_code' => 'BS', 'iso_code' => 'A3', 'full_name' => 'Bassas da India'], #unofficialISO
            ['fips_code' => 'BT', 'iso_code' => 'BT', 'full_name' => 'Bhutan'],
            ['fips_code' => 'BU', 'iso_code' => 'BG', 'full_name' => 'Bulgaria'],
            ['fips_code' => 'BV', 'iso_code' => 'BV', 'full_name' => 'Bouvet Island'],
            ['fips_code' => 'BX', 'iso_code' => 'BN', 'full_name' => 'Brunei'],
            ['fips_code' => 'BY', 'iso_code' => 'BI', 'full_name' => 'Burundi'],
            ['fips_code' => 'CA', 'iso_code' => 'CA', 'full_name' => 'Canada'],
            ['fips_code' => 'CB', 'iso_code' => 'KH', 'full_name' => 'Cambodia'],
            ['fips_code' => 'CD', 'iso_code' => 'TD', 'full_name' => 'Chad'],
            ['fips_code' => 'CE', 'iso_code' => 'LK', 'full_name' => 'Sri Lanka'],
            ['fips_code' => 'CF', 'iso_code' => 'CG', 'full_name' => 'Congo, Republic of the'],
            ['fips_code' => 'CG', 'iso_code' => 'CD', 'full_name' => 'Congo (Democratic Republic of the)'],
            ['fips_code' => 'CH', 'iso_code' => 'CN', 'full_name' => 'China'],
            ['fips_code' => 'CI', 'iso_code' => 'CL', 'full_name' => 'Chile'],
            ['fips_code' => 'CJ', 'iso_code' => 'KY', 'full_name' => 'Cayman Islands'],
            ['fips_code' => 'CK', 'iso_code' => 'CC', 'full_name' => 'Cocos (Keeling) Islands'],
            ['fips_code' => 'CM', 'iso_code' => 'CM', 'full_name' => 'Cameroon'],
            ['fips_code' => 'CN', 'iso_code' => 'KM', 'full_name' => 'Comoros'],
            ['fips_code' => 'CO', 'iso_code' => 'CO', 'full_name' => 'Colombia'],
            ['fips_code' => 'CQ', 'iso_code' => 'MP', 'full_name' => 'Northern Mariana Islands'],
            ['fips_code' => 'CR', 'iso_code' => 'A4', 'full_name' => 'Coral Sea Islands'], #unofficialISO
            ['fips_code' => 'CS', 'iso_code' => 'CR', 'full_name' => 'Costa Rica'],
            ['fips_code' => 'CT', 'iso_code' => 'CF', 'full_name' => 'Central African Republic'],
            ['fips_code' => 'CU', 'iso_code' => 'CU', 'full_name' => 'Cuba'],
            ['fips_code' => 'CV', 'iso_code' => 'CV', 'full_name' => 'Cabo Verde'],
            ['fips_code' => 'CW', 'iso_code' => 'CK', 'full_name' => 'Cook Islands'],
            ['fips_code' => 'CY', 'iso_code' => 'CY', 'full_name' => 'Cyprus'],
            ['fips_code' => 'DA', 'iso_code' => 'DK', 'full_name' => 'Denmark'],
            ['fips_code' => 'DJ', 'iso_code' => 'DJ', 'full_name' => 'Djibouti'],
            ['fips_code' => 'DO', 'iso_code' => 'DM', 'full_name' => 'Dominica'],
            ['fips_code' => 'DR', 'iso_code' => 'DO', 'full_name' => 'Dominican Republic'],
            ['fips_code' => 'DX', 'iso_code' => 'A5', 'full_name' => 'Dhekelia Sovereign Base Area'], #unofficialISO
            ['fips_code' => 'EC', 'iso_code' => 'EC', 'full_name' => 'Ecuador'],
            ['fips_code' => 'EG', 'iso_code' => 'EG', 'full_name' => 'Egypt'],
            ['fips_code' => 'EI', 'iso_code' => 'IE', 'full_name' => 'Ireland'],
            ['fips_code' => 'EK', 'iso_code' => 'GQ', 'full_name' => 'Equatorial Guinea'],
            ['fips_code' => 'EN', 'iso_code' => 'EE', 'full_name' => 'Estonia'],
            ['fips_code' => 'ER', 'iso_code' => 'ER', 'full_name' => 'Eritrea'],
            ['fips_code' => 'ES', 'iso_code' => 'SV', 'full_name' => 'El Salvador'],
            ['fips_code' => 'ET', 'iso_code' => 'ET', 'full_name' => 'Ethiopia'],
            ['fips_code' => 'EU', 'iso_code' => 'A6', 'full_name' => 'Europa Island'], #unofficialISO
            ['fips_code' => 'EZ', 'iso_code' => 'CZ', 'full_name' => 'Czechia'],
            ['fips_code' => 'FG', 'iso_code' => 'GF', 'full_name' => 'French Guiana'],
            ['fips_code' => 'FI', 'iso_code' => 'FI', 'full_name' => 'Finland'],
            ['fips_code' => 'FJ', 'iso_code' => 'FJ', 'full_name' => 'Fiji'],
            ['fips_code' => 'FK', 'iso_code' => 'FK', 'full_name' => 'Falkland Islands (Islas Malvinas)'],
            ['fips_code' => 'FM', 'iso_code' => 'FM', 'full_name' => 'Micronesia (Federated States of)'],
            ['fips_code' => 'FO', 'iso_code' => 'FO', 'full_name' => 'Faroe Islands'],
            ['fips_code' => 'FP', 'iso_code' => 'PF', 'full_name' => 'French Polynesia'],
            ['fips_code' => 'FR', 'iso_code' => 'FR', 'full_name' => 'France'],
            ['fips_code' => 'FS', 'iso_code' => 'TF', 'full_name' => 'French Southern and Antarctic Lands'],
            ['fips_code' => 'GA', 'iso_code' => 'GM', 'full_name' => 'Gambia, The'],
            ['fips_code' => 'GB', 'iso_code' => 'GA', 'full_name' => 'Gabon'],
            ['fips_code' => 'GG', 'iso_code' => 'GE', 'full_name' => 'Georgia'],
            ['fips_code' => 'GH', 'iso_code' => 'GH', 'full_name' => 'Ghana'],
            ['fips_code' => 'GI', 'iso_code' => 'GI', 'full_name' => 'Gibraltar'],
            ['fips_code' => 'GJ', 'iso_code' => 'GD', 'full_name' => 'Grenada'],
            ['fips_code' => 'GK', 'iso_code' => 'GG', 'full_name' => 'Guernsey'],
            ['fips_code' => 'GL', 'iso_code' => 'GL', 'full_name' => 'Greenland'],
            ['fips_code' => 'GM', 'iso_code' => 'DE', 'full_name' => 'Germany'],
            ['fips_code' => 'GO', 'iso_code' => 'A7', 'full_name' => 'Glorioso Islands'], #unofficialISO
            ['fips_code' => 'GP', 'iso_code' => 'GP', 'full_name' => 'Guadeloupe'],
            ['fips_code' => 'GQ', 'iso_code' => 'GU', 'full_name' => 'Guam'],
            ['fips_code' => 'GR', 'iso_code' => 'GR', 'full_name' => 'Greece'],
            ['fips_code' => 'GT', 'iso_code' => 'GT', 'full_name' => 'Guatemala'],
            ['fips_code' => 'GV', 'iso_code' => 'GN', 'full_name' => 'Guinea'],
            ['fips_code' => 'GY', 'iso_code' => 'GY', 'full_name' => 'Guyana'],
            ['fips_code' => 'GZ', 'iso_code' => 'A8', 'full_name' => 'Gaza Strip'], #unofficialISO
            ['fips_code' => 'HA', 'iso_code' => 'HT', 'full_name' => 'Haiti'],
            ['fips_code' => 'HK', 'iso_code' => 'HK', 'full_name' => 'Hong Kong'],
            ['fips_code' => 'HM', 'iso_code' => 'HM', 'full_name' => 'Heard Island and McDonald Islands'],
            ['fips_code' => 'HO', 'iso_code' => 'HN', 'full_name' => 'Honduras'],
            ['fips_code' => 'HR', 'iso_code' => 'HR', 'full_name' => 'Croatia'],
            ['fips_code' => 'HU', 'iso_code' => 'HU', 'full_name' => 'Hungary'],
            ['fips_code' => 'IC', 'iso_code' => 'IS', 'full_name' => 'Iceland'],
            ['fips_code' => 'ID', 'iso_code' => 'ID', 'full_name' => 'Indonesia'],
            ['fips_code' => 'IM', 'iso_code' => 'IM', 'full_name' => 'Isle of Man'],
            ['fips_code' => 'IN', 'iso_code' => 'IN', 'full_name' => 'India'],
            ['fips_code' => 'IO', 'iso_code' => 'IO', 'full_name' => 'British Indian Ocean Territory'],
            ['fips_code' => 'IP', 'iso_code' => 'A9', 'full_name' => 'Clipperton Island'], #unofficialISO
            ['fips_code' => 'IR', 'iso_code' => 'IR', 'full_name' => 'Iran (Islamic Republic of)'],
            ['fips_code' => 'IS', 'iso_code' => 'IL', 'full_name' => 'Israel'],
            ['fips_code' => 'IT', 'iso_code' => 'IT', 'full_name' => 'Italy'],
            ['fips_code' => 'IV', 'iso_code' => 'CI', 'full_name' => 'Cote d\'Ivoire'],
            ['fips_code' => 'IZ', 'iso_code' => 'IQ', 'full_name' => 'Iraq'],
            ['fips_code' => 'JA', 'iso_code' => 'JP', 'full_name' => 'Japan'],
            ['fips_code' => 'JE', 'iso_code' => 'JE', 'full_name' => 'Jersey'],
            ['fips_code' => 'JM', 'iso_code' => 'JM', 'full_name' => 'Jamaica'],
            ['fips_code' => 'JN', 'iso_code' => 'SJ', 'full_name' => 'Jan Mayen'],
            ['fips_code' => 'JO', 'iso_code' => 'JO', 'full_name' => 'Jordan'],
            ['fips_code' => 'JU', 'iso_code' => 'B1', 'full_name' => 'Juan de Nova Island'], #unofficialISO
            ['fips_code' => 'KE', 'iso_code' => 'KE', 'full_name' => 'Kenya'],
            ['fips_code' => 'KG', 'iso_code' => 'KG', 'full_name' => 'Kyrgyzstan'],
            ['fips_code' => 'KN', 'iso_code' => 'KP', 'full_name' => 'Korea (Democratic People\'s Republic of)'],
            ['fips_code' => 'KR', 'iso_code' => 'KI', 'full_name' => 'Kiribati'],
            ['fips_code' => 'KS', 'iso_code' => 'KR', 'full_name' => 'Korea (Republic of)'],
            ['fips_code' => 'KT', 'iso_code' => 'CX', 'full_name' => 'Christmas Island'],
            ['fips_code' => 'KU', 'iso_code' => 'KW', 'full_name' => 'Kuwait'],
            ['fips_code' => 'KV', 'iso_code' => 'XK', 'full_name' => 'Kosovo'],
            ['fips_code' => 'KZ', 'iso_code' => 'KZ', 'full_name' => 'Kazakhstan'],
            ['fips_code' => 'LA', 'iso_code' => 'LA', 'full_name' => 'Laos'],
            ['fips_code' => 'LE', 'iso_code' => 'LB', 'full_name' => 'Lebanon'],
            ['fips_code' => 'LG', 'iso_code' => 'LV', 'full_name' => 'Latvia'],
            ['fips_code' => 'LH', 'iso_code' => 'LT', 'full_name' => 'Lithuania'],
            ['fips_code' => 'LI', 'iso_code' => 'LR', 'full_name' => 'Liberia'],
            ['fips_code' => 'LO', 'iso_code' => 'SK', 'full_name' => 'Slovakia'],
            ['fips_code' => '--', 'iso_code' => 'UM', 'full_name' => 'United States Minor Outlying Islands'],
            ['fips_code' => 'LS', 'iso_code' => 'LI', 'full_name' => 'Liechtenstein'],
            ['fips_code' => 'LT', 'iso_code' => 'LS', 'full_name' => 'Lesotho'],
            ['fips_code' => 'LU', 'iso_code' => 'LU', 'full_name' => 'Luxembourg'],
            ['fips_code' => 'LY', 'iso_code' => 'LY', 'full_name' => 'Libya'],
            ['fips_code' => 'MA', 'iso_code' => 'MG', 'full_name' => 'Madagascar'],
            ['fips_code' => 'MB', 'iso_code' => 'MQ', 'full_name' => 'Martinique'],
            ['fips_code' => 'MC', 'iso_code' => 'MO', 'full_name' => 'Macau'],
            ['fips_code' => 'MD', 'iso_code' => 'MD', 'full_name' => 'Moldova (Republic of)'],
            ['fips_code' => 'MF', 'iso_code' => 'YT', 'full_name' => 'Mayotte'],
            ['fips_code' => 'MG', 'iso_code' => 'MN', 'full_name' => 'Mongolia'],
            ['fips_code' => 'MH', 'iso_code' => 'MS', 'full_name' => 'Montserrat'],
            ['fips_code' => 'MI', 'iso_code' => 'MW', 'full_name' => 'Malawi'],
            ['fips_code' => 'MJ', 'iso_code' => 'ME', 'full_name' => 'Montenegro'],
            ['fips_code' => 'MK', 'iso_code' => 'MK', 'full_name' => 'North Macedonia'],
            ['fips_code' => 'ML', 'iso_code' => 'ML', 'full_name' => 'Mali'],
            ['fips_code' => 'MN', 'iso_code' => 'MC', 'full_name' => 'Monaco'],
            ['fips_code' => 'MO', 'iso_code' => 'MA', 'full_name' => 'Morocco'],
            ['fips_code' => 'MP', 'iso_code' => 'MU', 'full_name' => 'Mauritius'],
            ['fips_code' => 'MR', 'iso_code' => 'MR', 'full_name' => 'Mauritania'],
            ['fips_code' => 'MT', 'iso_code' => 'MT', 'full_name' => 'Malta'],
            ['fips_code' => 'MU', 'iso_code' => 'OM', 'full_name' => 'Oman'],
            ['fips_code' => 'MV', 'iso_code' => 'MV', 'full_name' => 'Maldives'],
            ['fips_code' => 'MX', 'iso_code' => 'MX', 'full_name' => 'Mexico'],
            ['fips_code' => 'MY', 'iso_code' => 'MY', 'full_name' => 'Malaysia'],
            ['fips_code' => 'MZ', 'iso_code' => 'MZ', 'full_name' => 'Mozambique'],
            ['fips_code' => 'NC', 'iso_code' => 'NC', 'full_name' => 'New Caledonia'],
            ['fips_code' => 'NE', 'iso_code' => 'NU', 'full_name' => 'Niue'],
            ['fips_code' => 'NF', 'iso_code' => 'NF', 'full_name' => 'Norfolk Island'],
            ['fips_code' => 'NG', 'iso_code' => 'NE', 'full_name' => 'Niger'],
            ['fips_code' => 'NH', 'iso_code' => 'VU', 'full_name' => 'Vanuatu'],
            ['fips_code' => 'NI', 'iso_code' => 'NG', 'full_name' => 'Nigeria'],
            ['fips_code' => 'NL', 'iso_code' => 'NL', 'full_name' => 'Netherlands'],
            ['fips_code' => 'NM', 'iso_code' => 'B2', 'full_name' => 'No Man\'s Land'], #unofficialISO
            ['fips_code' => 'NO', 'iso_code' => 'NO', 'full_name' => 'Norway'],
            ['fips_code' => 'NP', 'iso_code' => 'NP', 'full_name' => 'Nepal'],
            ['fips_code' => 'NR', 'iso_code' => 'NR', 'full_name' => 'Nauru'],
            ['fips_code' => 'NS', 'iso_code' => 'SR', 'full_name' => 'Suriname'],
            ['fips_code' => '--', 'iso_code' => 'BQ', 'full_name' => 'Bonaire, Sint Eustatius and Saba'],
            ['fips_code' => 'NU', 'iso_code' => 'NI', 'full_name' => 'Nicaragua'],
            ['fips_code' => 'NZ', 'iso_code' => 'NZ', 'full_name' => 'New Zealand'],
            ['fips_code' => 'PA', 'iso_code' => 'PY', 'full_name' => 'Paraguay'],
            ['fips_code' => 'PC', 'iso_code' => 'PN', 'full_name' => 'Pitcairn Islands'],
            ['fips_code' => 'PE', 'iso_code' => 'PE', 'full_name' => 'Peru'],
            ['fips_code' => 'PF', 'iso_code' => 'B3', 'full_name' => 'Paracel Islands'], #unofficialISO
            ['fips_code' => 'PG', 'iso_code' => 'B4', 'full_name' => 'Spratly Islands'], #unofficialISO
            ['fips_code' => 'PK', 'iso_code' => 'PK', 'full_name' => 'Pakistan'],
            ['fips_code' => 'PL', 'iso_code' => 'PL', 'full_name' => 'Poland'],
            ['fips_code' => 'PM', 'iso_code' => 'PA', 'full_name' => 'Panama'],
            ['fips_code' => 'PO', 'iso_code' => 'PT', 'full_name' => 'Portugal'],
            ['fips_code' => 'PP', 'iso_code' => 'PG', 'full_name' => 'Papua New Guinea'],
            ['fips_code' => 'PS', 'iso_code' => 'PW', 'full_name' => 'Palau'],
            ['fips_code' => 'PU', 'iso_code' => 'GW', 'full_name' => 'Guinea-Bissau'],
            ['fips_code' => 'QA', 'iso_code' => 'QA', 'full_name' => 'Qatar'],
            ['fips_code' => 'RE', 'iso_code' => 'RE', 'full_name' => 'Reunion'],
            ['fips_code' => 'RI', 'iso_code' => 'RS', 'full_name' => 'Serbia'],
            ['fips_code' => 'RM', 'iso_code' => 'MH', 'full_name' => 'Marshall Islands'],
            ['fips_code' => 'RN', 'iso_code' => 'MF', 'full_name' => 'Saint Martin'],
            ['fips_code' => 'RO', 'iso_code' => 'RO', 'full_name' => 'Romania'],
            ['fips_code' => 'RP', 'iso_code' => 'PH', 'full_name' => 'Philippines'],
            ['fips_code' => 'RQ', 'iso_code' => 'PR', 'full_name' => 'Puerto Rico'],
            ['fips_code' => 'RS', 'iso_code' => 'RU', 'full_name' => 'Russia'],
            ['fips_code' => 'RW', 'iso_code' => 'RW', 'full_name' => 'Rwanda'],
            ['fips_code' => 'SA', 'iso_code' => 'SA', 'full_name' => 'Saudi Arabia'],
            ['fips_code' => 'SB', 'iso_code' => 'PM', 'full_name' => 'Saint Pierre and Miquelon'],
            ['fips_code' => 'SC', 'iso_code' => 'KN', 'full_name' => 'Saint Kitts and Nevis'],
            ['fips_code' => 'SE', 'iso_code' => 'SC', 'full_name' => 'Seychelles'],
            ['fips_code' => 'SF', 'iso_code' => 'ZA', 'full_name' => 'South Africa'],
            ['fips_code' => 'SG', 'iso_code' => 'SN', 'full_name' => 'Senegal'],
            ['fips_code' => 'SH', 'iso_code' => 'SH', 'full_name' => 'Saint Helena'],
            ['fips_code' => 'SI', 'iso_code' => 'SI', 'full_name' => 'Slovenia'],
            ['fips_code' => 'SL', 'iso_code' => 'SL', 'full_name' => 'Sierra Leone'],
            ['fips_code' => 'SM', 'iso_code' => 'SM', 'full_name' => 'San Marino'],
            ['fips_code' => 'SN', 'iso_code' => 'SG', 'full_name' => 'Singapore'],
            ['fips_code' => 'SO', 'iso_code' => 'SO', 'full_name' => 'Somalia'],
            ['fips_code' => 'SP', 'iso_code' => 'ES', 'full_name' => 'Spain'],
            ['fips_code' => '--', 'iso_code' => 'SS', 'full_name' => 'South Sudan'],
            ['fips_code' => 'ST', 'iso_code' => 'LC', 'full_name' => 'Saint Lucia'],
            ['fips_code' => 'SU', 'iso_code' => 'SD', 'full_name' => 'Sudan'],
            ['fips_code' => 'SV', 'iso_code' => 'SJ', 'full_name' => 'Svalbard'],
            ['fips_code' => 'SW', 'iso_code' => 'SE', 'full_name' => 'Sweden'],
            ['fips_code' => 'SX', 'iso_code' => 'GS', 'full_name' => 'South Georgia and the South Sandwich Islands'],
            ['fips_code' => 'NN', 'iso_code' => 'SX', 'full_name' => 'Sint Maarten'],
            ['fips_code' => 'SY', 'iso_code' => 'SY', 'full_name' => 'Syrian Arab Republic'],
            ['fips_code' => 'SZ', 'iso_code' => 'CH', 'full_name' => 'Switzerland'],
            ['fips_code' => 'TD', 'iso_code' => 'TT', 'full_name' => 'Trinidad and Tobago'],
            ['fips_code' => 'TE', 'iso_code' => 'B5', 'full_name' => 'Tromelin Island'], #unofficialISO
            ['fips_code' => 'TH', 'iso_code' => 'TH', 'full_name' => 'Thailand'],
            ['fips_code' => 'TI', 'iso_code' => 'TJ', 'full_name' => 'Tajikistan'],
            ['fips_code' => 'TK', 'iso_code' => 'TC', 'full_name' => 'Turks and Caicos Islands'],
            ['fips_code' => 'TL', 'iso_code' => 'TK', 'full_name' => 'Tokelau'],
            ['fips_code' => 'TN', 'iso_code' => 'TO', 'full_name' => 'Tonga'],
            ['fips_code' => 'TO', 'iso_code' => 'TG', 'full_name' => 'Togo'],
            ['fips_code' => 'TP', 'iso_code' => 'ST', 'full_name' => 'Sao Tome and Principe'],
            ['fips_code' => 'TS', 'iso_code' => 'TN', 'full_name' => 'Tunisia'],
            ['fips_code' => 'TT', 'iso_code' => 'TL', 'full_name' => 'Timor-Leste'],
            ['fips_code' => 'TU', 'iso_code' => 'TR', 'full_name' => 'Turkey'],
            ['fips_code' => 'TV', 'iso_code' => 'TV', 'full_name' => 'Tuvalu'],
            ['fips_code' => 'TW', 'iso_code' => 'TW', 'full_name' => 'Taiwan (Province of China)'],
            ['fips_code' => 'TX', 'iso_code' => 'TM', 'full_name' => 'Turkmenistan'],
            ['fips_code' => 'TZ', 'iso_code' => 'TZ', 'full_name' => 'Tanzania, United Republic of'],
            ['fips_code' => 'UC', 'iso_code' => 'CW', 'full_name' => 'Curacao'],
            ['fips_code' => 'UG', 'iso_code' => 'UG', 'full_name' => 'Uganda'],
            ['fips_code' => 'UK', 'iso_code' => 'GB', 'full_name' => 'United Kingdom of Great Britain and Northern Ireland'],
            ['fips_code' => 'UP', 'iso_code' => 'UA', 'full_name' => 'Ukraine'],
            ['fips_code' => 'US', 'iso_code' => 'US', 'full_name' => 'United States of America'],
            ['fips_code' => 'UV', 'iso_code' => 'BF', 'full_name' => 'Burkina Faso'],
            ['fips_code' => 'UY', 'iso_code' => 'UY', 'full_name' => 'Uruguay'],
            ['fips_code' => 'UZ', 'iso_code' => 'UZ', 'full_name' => 'Uzbekistan'],
            ['fips_code' => 'VC', 'iso_code' => 'VC', 'full_name' => 'Saint Vincent and the Grenadines'],
            ['fips_code' => 'VE', 'iso_code' => 'VE', 'full_name' => 'Venezuela (Bolivarian Republic of)'],
            ['fips_code' => 'VI', 'iso_code' => 'VG', 'full_name' => 'Virgin Islands (British)'],
            ['fips_code' => 'VM', 'iso_code' => 'VN', 'full_name' => 'Vietnam'],
            ['fips_code' => 'VQ', 'iso_code' => 'VI', 'full_name' => 'Virgin Islands (U.S.)'],
            ['fips_code' => 'VT', 'iso_code' => 'VA', 'full_name' => 'Holy See'],
            ['fips_code' => 'WA', 'iso_code' => 'NA', 'full_name' => 'Namibia'],
            ['fips_code' => 'WE', 'iso_code' => 'PS', 'full_name' => 'Palestine, State of'],
            ['fips_code' => 'WF', 'iso_code' => 'WF', 'full_name' => 'Wallis and Futuna'],
            ['fips_code' => 'WI', 'iso_code' => 'EH', 'full_name' => 'Western Sahara'],
            ['fips_code' => 'WS', 'iso_code' => 'WS', 'full_name' => 'Samoa'],
            ['fips_code' => 'WZ', 'iso_code' => 'SZ', 'full_name' => 'Eswatini'],
            ['fips_code' => 'YI', 'iso_code' => 'CS', 'full_name' => 'Serbia and Montenegro'],
            ['fips_code' => 'YM', 'iso_code' => 'YE', 'full_name' => 'Yemen'],
            ['fips_code' => 'ZA', 'iso_code' => 'ZM', 'full_name' => 'Zambia'],
            ['fips_code' => 'ZI', 'iso_code' => 'ZW', 'full_name' => 'Zimbabwe']
        ]);
    }
}
